### ISSUE TITLE
node app.js failed when i pull the latest codes (1.3)

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#10]
```
➜  asch git:(master) ✗ node app.js                                                                                     [108/1028]
log 2017-07-18 15:17:14 830 Asch started: 0.0.0.0:4096
fatal 2017-07-18 15:17:14 917 Error: Error: near line 163: table trs has no column named message

    at onerror (/home/yanyiwu/code/asch/src/dblite/index.js:252:24)
    at Socket.<anonymous> (/home/yanyiwu/code/asch/src/dblite/index.js:266:3)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:252:12)
    at readableAddChunk (_stream_readable.js:239:11)
    at Socket.Readable.push (_stream_readable.js:197:10)
    at Pipe.onread (net.js:589:20)
```

**Comment by yanyiwu** [comment]
```
rm -rf blockchain.db
```

Fixed.
