### ISSUE TITLE
npm test failed

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#16]
```
➜  asch git:(master) ✗ npm test

> asch@1.3.1 test /home/yanyiwu/code/asch
> mocha --require mocha-babel



(node:6771) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'hea
der' of undefined
(node:6771) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are
 not handled will terminate the Node.js process with a non-zero exit code.
  1) "before all" hook: callee$0$0

  0 passing (36ms)
  1 failing

  1)  "before all" hook: callee$0$0:
     TypeError: Cannot read property 'header' of undefined
      at Test._assertHeader (node_modules/supertest/lib/test.js:208:19)
      at Test._assertFunction (node_modules/supertest/lib/test.js:247:11)
      at Test.assert (node_modules/supertest/lib/test.js:148:18)
      at assert (node_modules/supertest/lib/test.js:127:12)
      at node_modules/supertest/lib/test.js:124:5
      at Test.Request.callback (node_modules/superagent/lib/node/index.js:687:12)
      at ClientRequest.<anonymous> (node_modules/superagent/lib/node/index.js:639:10)
      at Socket.socketErrorListener (_http_client.js:400:9)
      at emitErrorNT (internal/streams/destroy.js:62:8)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
```

https://travis-ci.org/yanyiwu/asch/jobs/257804728

**Comment by sqfasd** [comment]
测试前需要启动一个本地节点
这不是一个单元测试，算是一个集成测试吧
