### ISSUE TITLE
<fatal> init.js:382 (Domain.d.on) Domain peer { message: 'Cannot read property \'hostname\' of undefined',

### ISSUE THREAD

**Issue by ByCnck** [AschPlatform/asch#237]
### Version
1.4.1

### Steps to reproduce
2018-08-04T09:41:32+0800 <debug> plugin-rolodex.js:49 (EventEmitter.RolodexPlugin.node.router.events.on.identity) updating peer profile 1ec17363b0c736d34deefd051602db047fc78140
2018-08-04T09:41:32+0800 <debug> plugin-rolodex.js:49 (EventEmitter.RolodexPlugin.node.router.events.on.identity) updating peer profile 1e9678d3e8b8ac5554ab76df2fa0dc48bf51c1de
2018-08-04T09:41:32+0800 <debug> plugin-rolodex.js:49 (EventEmitter.RolodexPlugin.node.router.events.on.identity) updating peer profile 3867c76add9c7e358093404299497124e6fbe549
2018-08-04T09:41:32+0800 <debug> plugin-rolodex.js:49 (EventEmitter.RolodexPlugin.node.router.events.on.identity) updating peer profile 1f4da966f393af514f41a441a186728134c3a5ab
2018-08-04T09:41:32+0800 <fatal> init.js:382 (Domain.d.on) Domain peer { message: 'Cannot read property \'hostname\' of undefined',
  stack: 'TypeError: Cannot read property \'hostname\' of undefined\n    at RolodexPlugin.setExternalPeerInfo (/home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/lib/plugin-rolodex.js:115:22)\n    at EventEmitter.RolodexPlugin.node.router.events.on.identity (/home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/lib/plugin-rolodex.js:51:12)\n    at emitOne (events.js:116:13)\n    at EventEmitter.emit (events.js:211:7)\n    at Map.addContactByNodeId (/home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/lib/routing-table.js:100:17)\n    at KademliaNode._updateContactWorker (/home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/lib/node-kademlia.js:459:50)\n    at KademliaNode._updateContactQueue.async.queue (/home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/lib/node-kademlia.js:36:26)\n    at /home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/node_modules/async/dist/async.js:4082:9\n    at Object.process (/home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/node_modules/async/dist/async.js:2330:17)\n    at /home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/node_modules/async/dist/async.js:2238:19\n    at Immediate._onImmediate (/home/zhou/asch-linux-1.4.0-mainnet/node_modules/@kadenceproject/kadence/node_modules/async/dist/async.js:119:16)\n    at runCallback (timers.js:810:20)\n    at tryOnImmediate (timers.js:768:5)\n    at processImmediate [as _immediateCallback] (timers.js:745:5)' }
2018-08-04T09:41:42+0800 <debug> loader.js:215 (Loader.startSyncBlocks) startSyncBlocks enter
2018-08-04T09:41:42+0800 <debug> loader.js:221 (Function.library.sequence.add) startSyncBlocks enter sequence
2018-08-04T09:41:42+0800 <debug> peer.js:156 (Peer.randomRequest) select random contract [ 'b747a2eb1c72eabbbc3bdc55bfe7724cfe068731',
  { protocol: 'http:', hostname: '122.139.66.196', port: '8193' } ]
2018-08-04T09:41:44+0800 <error> loader.js:122 (modules.peer.randomRequest) Failed to request form random peer { err: 'Timeout',
  peer: 
   [ 'b747a2eb1c72eabbbc3bdc55bfe7724cfe068731',
     { protocol: 'http:', hostname: '122.139.66.196', port: '8193' } ] }
2018-08-04T09:41:44+0800 <debug> loader.js:230 (priv.loadBlocks) startSyncBlocks end
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer dbca5de481567094af13b21b563cac1bc8f4d2d9
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer 9f65ac673b916e94268b737f8f0f2ddb3e95a108
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer 9f65ac673b916e94268b737f8f0f2ddb3e95a108
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer 9f65ac673b916e94268b737f8f0f2ddb3e95a108
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer 9f65ac673b916e94268b737f8f0f2ddb3e95a108
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer f28c4415666db2360c5e228d020b70779e54e708
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer 9f65ac673b916e94268b737f8f0f2ddb3e95a108
2018-08-04T09:41:49+0800 <warn> plugin-quasar.js:295 (pullFilterFrom) failed to pull filter from 9f65ac673b916e94268b737f8f0f2ddb3e95a108, reason: Timed out waiting for response
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer f28c4415666db2360c5e228d020b70779e54e708
2018-08-04T09:41:49+0800 <warn> plugin-quasar.js:295 (pullFilterFrom) failed to pull filter from f28c4415666db2360c5e228d020b70779e54e708, reason: Timed out waiting for response
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer f28c4415666db2360c5e228d020b70779e54e708
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer f28c4415666db2360c5e228d020b70779e54e708
2018-08-04T09:41:49+0800 <debug> plugin-rolodex.js:55 (EventEmitter.RolodexPlugin.node.router.events.on.identity) removeing peer f28c4415666db2360c5e228d020b70779e54e708

**Comment by sqfasd** [comment]
Resolved at https://github.com/AschPlatform/asch-core/commit/0b29814cdb4d6f0345cc9bfd1b5fc2aafc968509
