### ISSUE TITLE
sodium install fail

### ISSUE THREAD

**Issue by ByCnck** [AschPlatform/asch#50]
```
     NEW_INT_PROP(crypto_stream_ ## ALGO ## _KEYBYTES); \
     ^~~~~~~~~~~~
../src/crypto_streams.cc:113:5: note: in expansion of macro ‘PROPS’
     PROPS(chacha20);
     ^~~~~
In file included from ../../nan/nan.h:197:0,
                 from ../src/include/node_sodium.h:20,
                 from ../src/crypto_streams.cc:8:
../../nan/nan_maybe_43_inl.h:116:35: note: declared here
 NAN_DEPRECATED inline Maybe<bool> ForceSet(
                                   ^~~~~~~~
/tmp/node_modules/sodium/install.js:288
            throw new Error(cmdLine + ' exited with code ' + code);
            ^

Error: make nodesodium exited with code null
    at ChildProcess.<anonymous> (/tmp/node_modules/sodium/install.js:288:19)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sodium@2.0.1 install: `node install.js --install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sodium@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/zhenxi/.npm/_logs/2017-11-17T09_54_38_233Z-debug.log

```

**Comment by ByCnck** [comment]
https://github.com/AschPlatform/asch/commit/a38e7dd0ce8df0f96cd3c9c3df7d23b98a60cb0e
https://github.com/AschPlatform/node-sodium/commit/bea31b75c7412762170cf9d33803444e263b89bd
