### ISSUE TITLE
run source code failed

### ISSUE THREAD

**Issue by yanyiwu** [AschPlatform/asch#7]
```
➜  asch git:(master) ✗ node app.js
log 2017-07-13 16:56:52 094 Asch started: 0.0.0.0:4096
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/yanyiwu/code/asch/node_modules/sodium/lib/sodium.js:16:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

➜  asch git:(master) ✗ node -v
v8.1.4
```

**Comment by yanyiwu** [comment]
I fixed the issue, that is because my node-gyp is out-of-date 

here is the solution: 

```
sudo npm install -g node-gyp
npm rebuild
node app.js
```
