### ISSUE TITLE
在docker下运行，创建dapp

### ISSUE THREAD

**Issue by David-tutu** [AschPlatform/asch#78]
输入asch-cli dapps -a之后
到 Enter DApp icon url https://yourdomain.com/logo.png这个步骤之后，报错信息如下
readline.js:1016
            throw err;
            ^

TypeError: AschJS.dapp.createDapp is not a function
    at module.exports.completed (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/plugins/dapps.js:186:27)
    at module.exports.PromptUI.onCompletion (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/inquirer/lib/ui/prompt.js:56:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:1826:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:1763:14)
    at AnonymousObserver.tryCatcher (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:1763:14)
    at InnerObserver.onCompleted (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:2885:65)
    at InnerObserver.tryCatcher (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:537:29)
    at AutoDetachObserverPrototype.completed (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:5435:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/root/.nvm/versions/node/v8.2.1/lib/node_modules/asch-cli/node_modules/rx-lite/rx.lite.js:1763:14)

linux版本没有这个问题

**Comment by ByCnck** [comment]
docker不是最新的，接下来的1.3.6版本会更新
